language: node_js
node_js:
  - "4.2"

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-test-dev lcov

script:
  - make build
  - make lint
  - make test
  - make coveralls
