language: node_js
node_js:
  - "4.2"

before_install:
  - npm install -g npm@3
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-test-dev lcov
  - sudo pip install cpplint

script:
  - make build
  - make lint
  - make test
  - make coveralls
